name: teyuto_player_analytics_example
description: Demonstrates how to use the teyuto_player_analytics plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  teyuto_player_analytics:
    path: ../
  video_player: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  video_player_android: 2.6.0

flutter:
  uses-material-design: true